-- Mariana Cruise Reservation System - Master SQL Query Script

DROP DATABASE IF EXISTS Cruise_Reservation_System;
CREATE DATABASE Cruise_Reservation_System CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE Cruise_Reservation_System;

-- Run order:
-- 1. Tables (in order below due to foreign keys)
--    - Personal.sql
--    - Ports.sql
--    - Cruise_Master.sql
--    - Cruise_Schedule.sql
--    - Suites.sql
--    - Activities.sql
--    - Booking_Status.sql
--    - Payment_Status.sql
--    - Reservation.sql
--    - Passengers.sql
--    - User_Suites.sql
--    - User_Activities.sql
--    - Payment.sql
--
-- 2. Functions
--    - Get_Total_Cost.sql
--
-- 3. Procedures
--    - Register_User.sql
--    - Create_Reservation.sql
--    - Make_Payment.sql
--    - uspGetEmail.sql
--    - uspGetUser.sql
--    - uspGetCruises.sql
--    - uspGetSuites.sql
--    - uspGetActivies.sql
--    - uspGetMe.sql
--    - uspGetTotalCost.sql
--    - uspGetReservationDetails.sql
--    - uspGetPassengers.sql
--    - uspGetUserSuites.sql
--    - uspGetUserActivities.sql
--    - uspUpdateProfile.sql
--    - uspUpdateReservation.sql
--    - uspDeletePassengers.sql
--    - uspInsertPassenger.sql
--    - uspDeleteUserSuites.sql
--    - uspInsertUserSuite.sql
--    - uspDeleteUserActivities.sql
--    - uspInsertUserActivity.sql
--    - uvMyBookings.sql
--
-- 4. Triggers
--    - after_payment.sql
--
-- 5. Views
--    - uvViewCruises.sql
--    - uvReservationDetails.sql
--    - Reservation_Summary.sql
--
-- 6. Seed Data
--    - seed_data.sql